#!/usr/bin/env python3
"""
Minimal single-prompt inference for nsys profiling.
Only calls the LLAISYS inference system — no HF model, no PyTorch warmup.

Usage:
  nsys profile -o results/nsys_out --force-overwrite true \\
    python test/profile/nsys_profile.py --model /path/to/model --input-len 512 --max-steps 16

  # Or with a custom prompt:
  python test/profile/nsys_profile.py --model /path/to/model --prompt "Hello world" --max-steps 32
"""

import argparse
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import llaisys
from transformers import AutoTokenizer

# ── Prompt bank for auto-generation ──────────────────────────
_PROMPT_SEEDS = {
    "en": (
        "The quick brown fox jumps over the lazy dog. "
        "Machine learning is a subset of artificial intelligence that enables systems "
        "to learn and improve from experience without being explicitly programmed. "
        "Deep learning uses neural networks with many layers to model complex patterns. "
    ),
    "zh": (
        "深度学习是机器学习的一个分支，它使用多层神经网络来建模复杂的模式。"
        "大语言模型通过自注意力机制处理序列数据，能够理解上下文并生成连贯的文本。"
        "GPU 并行计算极大地加速了神经网络的训练和推理过程。"
    ),
    "code": (
        "def fibonacci(n):\n"
        "    if n <= 1:\n"
        "        return n\n"
        "    return fibonacci(n-1) + fibonacci(n-2)\n\n"
        "class Transformer:\n"
        "    def __init__(self, d_model, n_heads):\n"
        "        self.attention = MultiHeadAttention(d_model, n_heads)\n"
        "        self.ffn = FeedForward(d_model)\n"
    ),
}


def _build_prompt(target_len: int, lang: str = "en") -> str:
    """Build a prompt of approximately target_len tokens by repeating seed text."""
    seed = _PROMPT_SEEDS.get(lang, _PROMPT_SEEDS["en"])
    # Repeat until we exceed target length, then trim
    prompt = seed
    while True:
        prompt += " " + seed
        # Rough estimate: ~4 chars per token for English, ~2 for Chinese
        cpt = 2 if lang == "zh" else 4
        if len(prompt) // cpt >= target_len * 1.5:
            break
    return prompt


def make_warmup_input(input_ids: list[int], vocab_size: int) -> list[int]:
    """Keep the measured shape while preventing a Prefix Cache hit."""
    if not input_ids:
        raise ValueError("warmup input must not be empty")
    if vocab_size <= 1:
        raise ValueError("vocab_size must be greater than one")

    warmup_ids = list(input_ids)
    warmup_ids[0] = (warmup_ids[0] + 1) % vocab_size
    if warmup_ids[0] == input_ids[0]:
        warmup_ids[0] = (warmup_ids[0] + 1) % vocab_size
    return warmup_ids


def main():
    parser = argparse.ArgumentParser(
        description="Single-prompt LLAISYS inference for nsys profiling")
    parser.add_argument("--model", required=True, help="Path to model directory")
    parser.add_argument("--prompt", default="", help="Custom prompt text")
    parser.add_argument("--input-len", type=int, default=50,
                        help="Target input token length (ignored if --prompt given)")
    parser.add_argument("--lang", default="en", choices=["en", "zh", "code"],
                        help="Prompt language for auto-generation")
    parser.add_argument("--max-steps", type=int, default=16,
                        help="Maximum new tokens to generate")
    parser.add_argument("--warmup-steps", type=int, default=2,
                        help="Tokens generated by the shape-matched warmup request")
    parser.add_argument("--no-warmup", action="store_true",
                        help="Skip warmup and measure cold-start behavior")
    parser.add_argument("--device", default="nvidia", choices=["nvidia"])
    parser.add_argument("--quantize-weights", action="store_true",
                        help="Enable W8A16 projection weights (meta quantize_weights=1)")
    parser.add_argument("--top_k", type=int, default=1)
    parser.add_argument("--top_p", type=float, default=1.0)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--output", default="", help="Path to save output tokens (optional)")

    args = parser.parse_args()
    if args.warmup_steps < 0:
        parser.error("--warmup-steps must be non-negative")

    # ── Tokenizer (HF, load-once for encode/decode) ──────────
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)

    # ── Prompt ───────────────────────────────────────────────
    if args.prompt:
        prompt = args.prompt
        input_ids = tokenizer.encode(prompt)
    else:
        # Build prompt, encode, and trim to exact target length
        seed = _build_prompt(args.input_len * 4, args.lang)  # generous seed
        # Apply chat template to get accurate token count
        content = tokenizer.apply_chat_template(
            conversation=[{"role": "user", "content": seed}],
            add_generation_prompt=True, tokenize=False,
        )
        input_ids = tokenizer.encode(content)
        # Trim to target length
        if len(input_ids) > args.input_len:
            input_ids = input_ids[:args.input_len]
        elif len(input_ids) < args.input_len:
            # Pad with repeated seed tokens
            while len(input_ids) < args.input_len:
                extra = tokenizer.encode(" " + _build_prompt(args.input_len, args.lang))
                input_ids = (input_ids + extra)[:args.input_len]
        prompt = tokenizer.decode(input_ids)

    input_len = len(input_ids)

    # ── LLAISYS model (no HF model loaded) ───────────────────
    device = llaisys.DeviceType.NVIDIA
    model = llaisys.models.load_causal_lm(
        args.model, device, quantize_weights=args.quantize_weights
    )

    gen_kwargs = dict(
        max_new_tokens=args.max_steps,
        top_k=args.top_k,
        top_p=args.top_p,
        temperature=args.temperature,
    )

    # ── Warmup ───────────────────────────────────────────────
    # Change the first token so the warmup has the same shape but cannot reuse
    # the measured request's cached prefix.
    warmup_steps = 0 if args.no_warmup else args.warmup_steps
    if warmup_steps:
        warmup_ids = make_warmup_input(input_ids, tokenizer.vocab_size)
        _ = model.generate(warmup_ids, max_new_tokens=warmup_steps, **{
            k: v for k, v in gen_kwargs.items() if k != "max_new_tokens"
        })

    # ── Timed inference ──────────────────────────────────────
    t0 = time.perf_counter()
    output_ids = model.generate(input_ids, **gen_kwargs)
    elapsed_s = time.perf_counter() - t0

    model.close()

    output_tokens = len(output_ids) - input_len

    # ── Summary ──────────────────────────────────────────────
    decoded = tokenizer.decode(output_ids[input_len:], skip_special_tokens=True)
    print(f"\n  quantize_weights: {args.quantize_weights}")
    print(f"  input: {input_len} tokens  output: {output_tokens} tokens  "
          f"elapsed: {elapsed_s:.2f}s  "
          f"throughput: {output_tokens / elapsed_s:.1f} tok/s")
    print(f"  warmup: {warmup_steps} tokens")
    print(f"  ttft: N/A (use nsys timeline)")
    print(f"\n  First 200 chars of output:\n  {decoded[:200]}...")

    if args.output:
        os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
        with open(args.output, "w") as f:
            f.write(decoded)
        print(f"\n  Output saved to: {args.output}")


if __name__ == "__main__":
    main()
